name: Generador de Posts
on: [push] # Se activa cada vez que guardas un cambio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar Node y Puppeteer
        run: |
          npm init -y
          npm install puppeteer
          
      - name: Ejecutar el Robot
        run: node generate.js
        
      - name: Guardar mis im√°genes
        uses: actions/upload-artifact@v4
        with:
          name: mis-imagenes-finales
          path: output/
